server:
  servlet:
    context-path: /
    session:
      timeout: 1440m
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://103.45.104.36:3000/eureka
spring:
  application:
    name: fitness-backend-edu
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#是否显示swagger
swagger:
  enabled: true
feign:
  httpclient:
    enabled: true
ribbon:
  eureka:
    enabled: true